# Generated by Django 4.2.6 on 2023-10-23 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_booking_no_of_guests_alter_menu_inventory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="Prince",
            new_name="Price",
        ),
    ]
